# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  run:
    cmds:
      - go run ./main.go ./model.go ./view.go ./stores.go
    silent: false
  build:
    cmds:
      - go build -o notty .
    silent: false